### ISSUE TITLE
Instructions don't match spec tests

### ISSUE THREAD

**Issue by marielfrank** [learn-co-curriculum/sinatra-basic-forms-lab#15]
**From the lab's instructions:**

> You can create this form in `views/create_puppy.erb`. Remember, you'll need to set up another controller action for a user to be able to view this form in the browser.

**Resulting spec errors:**

`1) App GET /NEW sends a 200 status code
     Failure/Error: expect(last_response.status).to eq(200)
       expected: 200
            got: 404

2) App GET /NEW renders the form
     Failure/Error: expect(page).to have_selector("form")
       expected #has_selector?("form") to return true, got false`

Tests passed after switching `views/create_puppy.erb` to `views/new.erb`.

**Comment by maxwellbenton** [comment]
Hi there,

Raising issues on GitHub should be reserved for problems with the curriculum — not difficulties solving a lab.

The issue here appears to be with your own code. If the error messages in the test suite are not providing enough information for you to diagnose the problem, try the following three things:

Run your code as it is intended to be run. That is, don't simply rely on the test suite to check the functionality of your code — check it yourself! For Ruby code, add some lines to the bottom of the file that call your methods and output verifiable information to the terminal. For Sinatra or Rails applications, fire up your local server and try executing the same actions that the test suite is failing to complete. For JavaScript code, open up your browser's JS console, paste in your code, and play around with your functions and variables.
Use Pry to poke around your Ruby (or Sinatra), Rails, or JavaScript code step-by-step. Check that the values of particular variables are what you expect them to be at various points throughout the program's execution.
Use the Ask a Question (AAQ) feature, where the Technical Coaches (on supported tracks) and fellow community members can help you figure it out. For some tips on how to take full advantage of AAQ, check out this helpful article in the Learn Help Center.
If, after reviewing your code and consulting AAQ, you still feel that this is an issue with the curriculum itself, please reopen the issue and provide more detail about why it's a curriculum issue, the steps needed to reproduce the issue, and any additional relevant information about your development environment (local or IDE).

Thanks! 💙
